### Register API
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username":"mohamed",
  "email":"mohamedmrslan@gmail.com",
  "phone":"01152432513",
  "password":"Mohamed#01152",
  "gender":"male"
}