# Get me
GET http://localhost:3000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZjQ3MDhjMWE5YTQ3M2ZmMTg4Y2NjNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc2MTEwOTY4NiwiZXhwIjoxNzYxNzE0NDg2fQ.jTYyrsI7LT66FQST2HK_IbOo47xu4X9ZzheTyyXR-Ak